### PR TITLE
Device Setup & Anaglyph

### PR DESCRIPTION
**Pull request by vbousquet**
This PR is made after a full review of the SDL initialization sequence, the video options and of the different stereo modes.

**Video options**
Video options were reviewed leading to the following changes:
- removed unused options from the VR panel
- clean up display mode selection, using the one from VPX (this should solve https://github.com/vpinball/vpvr/issues/26 but I did not test it yet)
- disabled options that are not implemented, and show the only available option when there is no choice (parallax, AO,...)

**Device setup**
There were quite a few differences between VPVR and VPX due to the fact that SDL needs to create its window while DX creates its context in a window created before hand. I rewrote this part to have a common & simpler API for the 2. This allows to share the player/render device initialization code between VPVR/VPX (excepted for SDL/DX native stuff) and will help further changes.

**Stereo modes & Anaglyph**
Regarding anaglyph and stereo mode beside VR: the code was broken for stereo and unimplemented for anaglyph so I rewrote it. It works really well. This gives really good results (fairly better than the parallax implementation available in VPX since this is a real stereo from 2 viewpoints render). I initially planned to port the parallax stereo from VPX as well but in the end, it appears to be a bad idea: the result will be less good in quality and performance, and advanced postprocess (AA,...) won't be possible. So I just disabled the parallax option for the moment in the options UI.
I have made quite a lot of test on this (desktop, fullscreen, all the stereo modes,...) but this is a quite large change so I may have miss things. I hope it is clean to be merged though. With this PR, things are looking good and not too far away for clean post process (AO, mirror, SSRefl) and static support (highly antialiased prerendered static parts). 

Also the distance between the 2 codebases is finally getting quite low, but there will be some decision to take on this (integration or not of VPVR capture capabilities to VPX, option dialog merging or not,...) and I don't know how you would want to discuss this. If you want I can contact on Discord, or propose something, or perhaps open an issue, or if you have clear opinions on these, just tell me. It will be as you like.

Regards,

   Vincent

### CODE REVIEW

**Comment by toxieainc** [comment]
Thanks for revamping the stereo code! Nowadays this is really the way to go, gfx cards are fast enough.

Apart from that, i'm all for a complete merge. Maybe, if its possible, in the beginning to still have a define to switch between the 2 compilation/runtime modes, then, ideally a dynamic switch during runtime (but then again, the latter is not really important i'd say).

**Comment by toxieainc** [comment]
..but maybe we should do a VPX 10.7.1 release before the complete merge??

**Comment by vbousquet** [comment]
I agree that a VPX 10.7.2 release would be a really good thing. There are a few good things in it and I did not see any new issue rising on the VPX side lately. It seems good to go.

Also, I have developped a tool for building the table by baking HDR lighting (see https://github.com/vbousquet/vpx_lightmapper) that has been used for a few tables by the VPinWorkshop members. The tables are ready to be released (and quite impressive too), just waiting for VPX to be released since they need 10.7.2 features (additive prim, HDR support, memory management fix). I think iaakki also use additive primitives for light/flashers and he may have one table waiting for the 10.7.2 release.

**Comment by jsm174** [comment]
Hello. After rebasing macos port:

https://github.com/vpinball/vpvr/blob/39ab197fae82721d76fc58ea91c178ca041d38ce/RenderDevice.cpp#L934-L948

This section might need to be wrapped in a `#ifdef ENABLE_VR`?

`m_scale` is only defined if `ENABLE_VR`


I can't compile with `ENABLE_VR` since OpenVR doesn't support macos.

**Pull request merged**
