### PR TITLE
Bloom: align to VPX

### PR DESCRIPTION
**Pull request by vbousquet**
Fix Bloom:
- use kernel 39 (instead of 19h)
- fix FS quad initialization (there were 3 initialization places with different values)
- remove FS quad offsetting in shader to align to VPX behavior (easier to maintain, insignificant performance impact)

Still, the quad initialization is a bit surprising since it is a member of RenderDevice, destroyed by RenderDevice but initialized externally by pin3d. I don't really get why but did not touch it (align to VPX code).

Tested on desktop and works well.

### CODE REVIEW

**Comment by toxieainc** [comment]
Thanks! To be honest, i don't remember why the quad init is done in pin3d. Weird.

**Comment by jsm174** [comment]
Great stuff!

Quick findings.. I rebased macos last night, and I did have to slightly modify the FBShader. (It was failing to compile, probably older macos opengl).

Anyway, it didn't like:

`const float offset39x39[10] = { ... };`

I was able to use:

`const float offset39x39[10] = float[] ( ... );`

**Comment by toxieainc** [comment]
Good catch, will add.

**Comment by vbousquet** [comment]
Yes, good catch. I need to use a glsl validator on these. Just testing with the driver compiler is not sufficient, and I will tackle the other FB shaders soon (stereo, AO, all AA...) so I need to be more careful on these.

I'm thinking of adding a (very simple) effect framework. There is one that has been developed (for GL only) but there are "not that clean" things in this part and it is only on GL side with lots of duplication and some errors/missings. To be clear, that is what an effect framework would do:
- handle gs/vs/ps shader combinations (so called techniques, move them out of the hlsl/glsl effect file to a common c++ side)
- handle states at the shader class level (like today), and apply them when bound (during begin/end), that is to say when context is resolved (technique, uniforms, samplers)
- move default state and texture bind to uniform handles (move them out of the hlsl effect file to a common c++ side)

The expected benefits for VPX/VPVR would be:
- VPX: do not rely anymore on the 10 years deprecated DX9 effect framework (I think allowing a fairly easy port to DX11),
- Both: move default sampler states and sampler unit binding in a common place (C++ side),
- Both: clean up state management (for the time being states are sometime defined through D3DX effect framework, sometimes directly through DX/GL calls)
- Both: give a better feedback on state change (these are counted on the VPX side but not when they are actually changed, that is to say when D3DX process the change when Begin si called, giving a count slightly off I think)
- VPVR: clean up effect management, and merge most code with the DX version

@toxieainc What do you think ? Would you be ok with this change, if done correctly ?

**Comment by jsm174** [comment]
cool. If there is any work done on ShaderGL parsing, some more notes. I've been lucky to get away with [minimal changes](https://github.com/vpinball/vpvr/compare/master...jsm174:vpvr:feature/macos#diff-56f254e75b12a2b46e4088d484f79fcf34542e66520faef69ac5aedcb7d8f1b8).

- some cr/lf issues (rewrite lines with a regex)
- macos can't go any higher than 410 (rewrite to 410 and add `#define __APPLE__` to use for `#ifndef`)
- all `#extension` need to be immediately after `#version 410`, so capture them and move them up.

**Comment by vbousquet** [comment]
For the time being, I'm not planning of rewriting all the shaders, just the frame buffer ones in order to align post processing with VPX, and fix some issues (stereo mode not all working, AO not working, missing post processes,...).

If we were to rewrite them (but again, just if, it's not a priority for me and I doubt I will find the free time for this), I would go for GL ES instead of GL. This would allow to use Google's Angle which should give quite a few benefit other DX/GL: better stability across drivers, easier portability, likely a bit of performance too (through Vulkan/Metal/DX11 which, I think, have better management of library calls perf impact).

But we can backport your change as is in the current shader as a first step :)

**Pull request merged**
