### PR TITLE
Makes VPVR rendering match VPX except post process

### PR DESCRIPTION
**Pull request by vbousquet**
Following previous PR and discussion, I have spent quite some time comparing VPVR / VPX. There were quite some visible differences so I dug for the causes. Two days later, here is a large PR that fixes the bugs affecting the rendering (not the post processing) that I have found.

To be precise it fixes the following points:
- match texture filtering with VPX (has impact on the environment lighting) and texture clamping on U and on V (needed for environment as well)
- fix vec4 uniform not being applied (fix the second scene light being entirely incorrect)
- fix numeric error in GLSL `normalize` (this would cause lighting artefacts)
- apply global emission scale to scene lights (fix the lighting level, likely a hack around previous bugs regarding the second light being wrong and the numeric errors causing artefacts)
- fix textbox sRGB / RGB colors
- fix error when setting a null texture (this was resulting in wrong reflections on balls without a decal)

I have performed quite some tests and they all passed, but all my test are desktop only and with a large change like this one, I can not guarantee that it will be harmless, but I think it really improves the application.

Here is my last comparison of VPVR vs VPX with these changes.

VPX rendering of the default full scene:
VPX

VPVR rendering of the default full scene with these changes:
VPVR

VPVR rendering of the default full scene without:
VPVR before

### CODE REVIEW

**Comment by vbousquet** [comment]
The PR was updated with more cleanups:
- add clang format
- port VPX formating to ease folder comparison (I use Idea folder comparison which is great to analyze the differences)
- improve the fix for multithreaded texture loading by disabling downscaling during the first multithreaded pass (I have tables where the testure get downscaled due to the multithreaded loading getting low on memory)
- fixed ball reflections. The playfield reflection on ball still need more checks

**Comment by vbousquet** [comment]
The added commits improve on the previous PR by:
- fixing the playfield ball reflection (the bug was on the initial ball shader fix, just above). There should not need any more fix on this
- fixing some random crashes due to incorrect buffer management
- fixing ramps being slightly different between VPX and VPVR
- fixing some remaining lighting issues
- preparing for more code cleanup in order to reduce the gap between VPVR and VPX

**Comment by toxieainc** [comment]
As i'm a bit confused by your other comment in vpinball/vpinball: So should this be already merged, or should i wait some more?

btw: I haven't checked all commits in detail yet, but saw a clang format mentioned. Please do not use this unless it really makes sense/locally. Otherwise the history/blame of files gets very tedious to work with in practice. Thanks!!

**Comment by toxieainc** [comment]
..all good though, just checked the commits, sorry for the noise  ;)

**Comment by vbousquet** [comment]
My bad, I wasn't that clear with this PR intent, and I should have splitted it in 2 different parts. Anyway, here are some better explanations.

The initial intent of this PR was to fix differences in rendering between VPVR and VPX. This lead to commits [fca6915](https://github.com/vpinball/vpvr/pull/11/commits/fca6915445dbb9d54261ce8e2527c7d7b1b74eeb), [7c28382](https://github.com/vpinball/vpvr/pull/11/commits/7c283821ba43ab9cf3a9c8666f901187aea6ccb8), [70062a1](https://github.com/vpinball/vpvr/pull/11/commits/70062a188bbe7f13c72366a1a424b03f427a3ee0), [15312f2](https://github.com/vpinball/vpvr/pull/11/commits/15312f262de23db9250e03374a433c26790f9f95), [ba7955d](https://github.com/vpinball/vpvr/pull/11/commits/ba7955dc4ca7822dbf3459da80dcdbb0e98eed4f), [76cf61c](https://github.com/vpinball/vpvr/pull/11/commits/76cf61c4214d7b6af81fef744848031b01e32422), [3497ce6](https://github.com/vpinball/vpvr/pull/11/commits/3497ce66ee18f775aca2a2be65b15d53bb9aca4e), [d0363d2](https://github.com/vpinball/vpvr/pull/11/commits/d0363d2223435b4aa8106b9ce5a63df708c1e5e4), [f35b9d9](https://github.com/vpinball/vpvr/pull/11/commits/f35b9d90a7455fe3622938bb313e26d4889977e6), [6eebb37](https://github.com/vpinball/vpvr/pull/11/commits/6eebb372020e072834ca5ff423a2f35bb81629d0), [f49e3b6](https://github.com/vpinball/vpvr/pull/11/commits/f49e3b60b531bd17d31f427625a1770011317d92). After all these commits, quite a few rendering bugs were solved, and the codebase has been moved toward VPX codebase (less code differences). This correspond to the work until my last comment above.

Still, after these commits, I identified some remaining fixes, and also started to believe that it would be achievable to have VPVR actually fully match VPX. So I dug for more in depth changes in order to reach this goal. This lead to [af60e36](https://github.com/vpinball/vpvr/pull/11/commits/af60e36c4bc33556424ccd66e732078bfc58a4e7) and an un-pushed yet upcoming commit. So right now, until I push the "Part II" commit, this PR should **NOT** be merged since while [af60e36](https://github.com/vpinball/vpvr/pull/11/commits/af60e36c4bc33556424ccd66e732078bfc58a4e7) moves in the right direction, it also has issues for VPVR that will be fixed in the next commit. Sorry for that, I should have commented it (initially, I hoped to push the "part II" commit just after the part I, but it was not that simple...).

To sum it up, here is the state after the aforementioned commits:

- [x] fix incorrect ball reflection when there is no decal (this was due to unimplemented SetTextureNull)
- [x] fix scene lights not being applied correctly (this was due to a bug where float4[] uniforms were not applied, and missing global emission scale)
- [x] fix lighting artefact (GLSL numeric problem when using normalize with high half float values)
- [x] fix overall lighting differences (filtering/clamping and sRGB/RGB issues)
- [x] fix multithreaded loading downsizing texture on low memory

And here are the remaining goals:

- [ ] remove unneeded differences between the codebase (makes VPVR actually match VPX regarding formatting, code position, naming,...) - Progress: largely done in "Part II" commit, but could be improved
- [ ] bring latest changes from VPX to VPVR (anaglyph, sharpen,...) - Progress: ready, included in "Part II" commit
- [ ] make DX9 build target actually work and fully match VPX - Progress: ready, included in "Part II" commit (still need some love on the project file to build for Windows XP)
- [ ] reimplement the postprocess to actually match VPX - Progress: working on it at the moment
- [ ] add the static pre-rendering (except when in camera/VR mode) - Progress: to be done

So there is still some work but it has been progressing steadily and I'm starting to hope to succeed. In the end, the amount of differences between VPVR and VPX should be actually **lower** since I'm doing this by using a code compare tool (Idea's folder comparison between VPVR and VPX) and aligning VPVR to VPX when applicable or re-implementing/adapting to OpenGL when needed. Beside, if I identify things that I think should be changed on both sides, I will also prepare a PR for VPX.

The clang commits is not a reformating, but just adding the clang format file to ensure that VPVR formatting matches VPX's one, without changing the existing code.

In the end, eventually, if everything goes well and tests passes, this would open a possibility of creating a PR on VPX to merge the 2 codebases there (on the VPX repo, starting by a commit for VPX with the change on both side if needed, then a commit to add to VPX the VPVR build targets).

**Comment by toxieainc** [comment]
Oh wow, you move pretty fast currently..  :)

As for: 'add the static pre-rendering (except when in camera/VR mode)': my personal opinion on this: don't bother, as we wanted to move in the fully dynamic direction anyway over time. But with DX9 its simply too complicated/unintuitive to get the same performance as with the static rendering. With newer GL versions (or DX1x or Vulkan) its much easier.

**Comment by vbousquet** [comment]
Finally, I have worked on this more in depth. It leads to larger changes that I expected. So I have splitted the things as I should have done from the beginning. The last force push removed the changes that were not fully finished in order to put this PR in a clean, mergeable state, that is to say just containing the aforementioned fixes:
- fix incorrect ball reflection when there is no decal (this was due to unimplemented SetTextureNull)
- fix scene lights not being applied correctly (this was due to a bug where float4[] uniforms were not applied, and missing global emission scale)
- fix lighting artefact (GLSL numeric problem when using normalize with high half float values)
- fix overall lighting differences (filtering/clamping and sRGB/RGB issues)
- fix multithreaded loading downsizing texture on low memory

This PR **should** be merged and tested. It should improve VPVR on all these things without breaking anything.

The VPX/VPVR convergence will be made in clean separated PRs. Sorry for the inconvenience.

**Comment by toxieainc** [comment]
Neat! And no problem at all. Thanks for being the brave one to clean up/unify that fork!

**Comment by toxieainc** [comment]
Great! I just quickly tested it and i think this is the first time i saw the VPVR rendering nice and clean in 'normal' desktop mode! Cool!

**Comment by jsm174** [comment]
With all these change I was dreading a rebase, but I only had 2 conflicts! Amazing!!

Would it be possible in a future PR to move the `TextureFilter` enum somewhere else? I temporarily moved it to `Texture.h`:

```
[build] [12/97   3% :: 1.080] Building CXX object CMakeFiles/vpinball.dir/inc/gpuprofiler.cpp.o
[build] FAILED: CMakeFiles/vpinball.dir/inc/gpuprofiler.cpp.o 
[build] /usr/bin/clang++ -DENABLE_INI -DENABLE_SDL -DENABLE_SDL_INPUT -DIMGUI_IMPL_OPENGL_LOADER_CUSTOM -DTWEAK_GL_SHADER -DWINE_UNICODE_NATIVE -D__WINESRC__ -D__forceinline="__attribute__((always_inline)) inline" -I/Users/jmillard/git/vpvr/pin -I/Users/jmillard/git/lll/vpvr/media -I/Users/jmillard/git/lll/vpvr/inc -I/Users/jmillard/git/lll/vpvr/inc/pole -I/Users/jmillard/git/lll/vpvr/inc/wine/include -I/Users/jmillard/git/lll/vpvr/inc/wine/dlls/vbscript -I/Users/jmillard/git/lll/vpvr/inc/wine/dlls/oleaut32 -I/Users/jmillard/git/lll/vpvr/inc/wine/dlls/kernelbase -I/Users/jmillard/git/lll/vpvr/imgui -I/Users/jmillard/git/lll/vpvr/imgui/implot -I/Users/jmillard/git/lll/vpvr -I/opt/homebrew/include/SDL2 -I/Users/jmillard/git/lll/vpvr/inc/glad_41 -isystem /opt/homebrew/include -Wno-pragma-pack -Wno-inconsistent-missing-override -Wno-missing-exception-spec -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT CMakeFiles/vpinball.dir/inc/gpuprofiler.cpp.o -MF CMakeFiles/vpinball.dir/inc/gpuprofiler.cpp.o.d -o CMakeFiles/vpinball.dir/inc/gpuprofiler.cpp.o -c /Users/jmillard/git/lll/vpvr/inc/gpuprofiler.cpp
[build] In file included from /Users/jmillard/git/vpvr/inc/gpuprofiler.cpp:1:
[build] In file included from /Users/jmillard/git/vpvr/stdafx.h:157:
[build] In file included from /Users/jmillard/git/vpvr/main_osx.h:1190:
[build] In file included from /Users/jmillard/git/vpvr/vpinball_h.h:12:
[build] In file included from /Users/jmillard/git/vpvr/RenderDevice.h:12:
[build] /Users/jmillard/git/vpvr/TextureManager.h:10:6: error: ISO C++ forbids forward references to 'enum' types
[build] enum TextureFilter;
[build]      ^
[build] 1 error generated.
```

**Comment by vbousquet** [comment]
@jsm174 TextureFilter should disappear in an upcoming PR regarding how sampler uniform are managed (right now, it's a somewhat messy since this is spread between C++ and HLSL files, spread across the classes, and also with silent state changes through D3DX superseeded by direct state change on hard coded sampler units).

The next commits I have to tidy up and sync between VPX / VPVR are the following:
- initial VPVR bug fix => done (this one)
- RenderTarget/Sampler abstraction => done (submitted for VPX, upcoming for VPVR)
- clean Shader sampler uniform management (move the sampler filtering, texture unit binding,... in one single place, on the C++ side). This replace the TextureFilter enum with a SamplerFilter one => nearly finished, to be submitted
- clean Shader state management (for the time being, you have a mixed state management for DX9 between D3DX and direct state access, and an application state management for OpenGL) => to be done (rewrite of the shader code in a single clean Shader.h/Shader.cpp)
- align VPVR render path to the one of VPX, including review and cleanup of postprocessing => partially done

**Comment by jsm174** [comment]
awesome. Can't wait!!

**Pull request merged**
